name: Build Jupyter Book

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - name: Check out repository
      uses: actions/checkout@v3

    # Step 2: Set up Miniconda
    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: base
        auto-update-conda: true

    # Step 3: Install Jupyter Book and nb_conda_kernels
    - name: Install Jupyter Book and dependencies
      run: |
        conda install -c conda-forge jupyter-book nb_conda_kernels -y

    # Step 4: Set up Conda environments for each kernel
    - name: Set up Conda environments
      run: |
        for env_file in $(find recipes/* -name "env.yml"); do
          env_name=$(basename $(dirname $env_file))  # Use the directory name as the environment name
          echo "Creating environment $env_name from $env_file"
          conda env create -f $env_file -n $env_name || conda env update -f $env_file -n $env_name
          conda run -n $env_name python -m ipykernel install --user --name=$env_name --display-name "Python ($env_name)"
        done

    # Step 5: Build the Jupyter Book
    - name: Build Jupyter Book
      run: |
        jupyter-book build my_book/

    # Step 6: Upload the built book as an artifact
    - name: Upload HTML output
      uses: actions/upload-artifact@v3
      with:
        name: jupyter-book-html
        path: my_book/_build/html/
