# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Gammapy recipes
author: The Gammapy team
logo: gammapy_logo.png

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  kernel_spec_manager_class: nb_conda_kernels.CondaKernelSpecManager
  timeout: 1200        # Allow 20 minutes per cell
  execute_notebooks: cache           # Use cache for previously executed outputs


# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/executablebooks/jupyter-book  # Online location of your book
  path_to_book: docs  # Optional path to your book, relative to the repository root
  branch: master  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true
